export enum ItemType {
  MONITOR = "MONITOR",
  TABLE = "TABLE",
  LAPTOP = "LAPTOP",
  DOCKING_STATION = "DOCKING STATION",
  CHAIR = "CHAIR",
  WEBCAM = "WEBCAM",
  KEYBOARD = "KEYBOARD",
  HEADPHONES = "HEADPHONES",
  OTHER = "OTHER",
}
