stages:
  - merge
  - setup
  - build
  - deploy

cache:
  key: $CI_PIPELINE_ID
  policy: pull
  untracked: true

merge_staging_to_production:
  stage: merge
  image:
    name: node:18
    pull_policy: if-not-present
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
  before_script:
    - git config --global user.email $BOT_EMAIL
    - git config --global user.name $BOT_NAME
  script:
    - git checkout "staging"
    - git checkout $CI_COMMIT_BRANCH
    - git merge "staging"
    - git push -u $GITLAB_PROJECT_ORIGIN $CI_COMMIT_BRANCH
  tags:
    - ah3-docker

install_modules:
  stage: setup
  image: node:18
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
  before_script:
    - git config --global user.email $BOT_EMAIL
    - git config --global user.name $BOT_NAME
    - git config --global pull.rebase true
  script:
    - git checkout -f $CI_COMMIT_BRANCH && git pull
    - npm install -g --force yarn
    - yarn install --frozen-lockfile --no-progress
  cache:
    key: $CI_PIPELINE_ID
    policy: pull-push
    paths:
      - .yarn
      - node_modules
  tags:
    - ah3-docker

build_application:
  stage: build
  image:
    name: node:18
    pull_policy: if-not-present
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
  before_script:
    - export VITE_APP_PUBLIC_URL=$PUBLIC_URL
    - export VITE_APP_HOST_CORE=$HOST_CORE
    - export VITE_APP_HOST_IDP=$HOST_IDP
    - export VITE_APP_HOST_APPSHUB=$HOST_APPSHUB
    - export VITE_APP_REALM=$REALM
    - export VITE_APP_CLIENT_ID=$CLIENT_ID
    - export VITE_APP_MOCKED=$MOCKED
    - git config --global user.email $BOT_EMAIL
    - git config --global user.name $BOT_NAME
    - git config --global pull.rebase true
  script:
    - git checkout -f $CI_COMMIT_BRANCH && git pull
    - CI=false yarn build
  artifacts:
    expire_in: 1 hour
    paths:
      - build/*
  tags:
    - ah3-docker

deploy_to_production:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
  script:
    - cp -rf build/* /var/www/$LOCATION/
  tags:
    - ah3-shell
